name: My.Extensions.Localization.Json

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build windows-latest
    runs-on: windows-latest
    steps:
    - name: Checkout source code
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release -f net7.0
    - name: Test
      run: dotnet test -c Release
